name: Release new statblocks package
on:
  push:
    branches:
      - main
      
jobs:

  build-project:
    runs-on: ubuntu-latest
    name: Collent invididual files
    steps:
    - uses: actions/upload-artifact@v3
      with:
          name: world-of-darkness-statblocks
          path: /css-snippets

  release-project:
      name: Release
      runs-on: ubuntu-latest
      steps: 
        - name: Download all files
          uses: actions/download-artifact@v3
        - name: Display structure of downloaded files
          run: ls -R