name: Release new statblocks package
on:
  push:
    paths:
      - '**.yml'
      - '**.yaml'
      
jobs:

  build-project:
    name: Build and collect everything
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code 
        uses: actions/checkout@v4
      - name: Collent all files into one archive
        uses: actions/upload-artifact@v4
        with:
            name: world-of-darkness-statblocks
            path: | 
              fantasy-statblock-jsons/
              css-snippets/
              js/WoDCharsheets.js
            if-no-files-found: error
      - name: Collent all files into one archive
        uses: actions/upload-artifact@v4
        with:
            name: jsons
            path: fantasy-statblock-jsons/
            if-no-files-found: error


  release-project:
      runs-on: ubuntu-latest
      name: Release
      needs: build-project
      steps: 
        - name: Download all files
          uses: actions/download-artifact@v4
        - name: Display structure of downloaded files
          run: ls -R
        - name: Create GH release
          uses: actions/create-release@v1
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            tag_name: ${{ github.run_number }}
            release_name: Release ${{ github.run_number }}