name: Release new statblocks package
on:
  push:
    paths:
      - '**.yml'
      
jobs:

  build-project:
    runs-on: ubuntu-latest
    defaults: 
      run:
        working-directory: /home/runner/work/silentjames/wod-charsheets-for-obsidian/
    name: Collent invididual files
    steps:
    - run: cd ./ && ls
    - uses: actions/upload-artifact@v4
      with:
          name: world-of-darkness-statblocks
          path: js
          if-no-files-found: error

  release-project:
      runs-on: ubuntu-latest
      name: Release
      needs: build-project
      steps: 
        - name: Download all files
          uses: actions/download-artifact@v3
        - name: Display structure of downloaded files
          run: ls -R